[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "1"

[[bin]]
name = "2"

[[bin]]
name = "3"

[[bin]]
name = "4"

[dependencies]
